#! /usr/bin/env python3

import time
from rich.panel import Panel
from rich.console import Console
from rich import print
import csv
import argparse
from pathlib import Path
from dotenv import load_dotenv
import os
import getpass
import requests
from rich.text import Text
from datetime import datetime
from random import random

help_msg = """
"""
parser = argparse.ArgumentParser(add_help=False)

args = parser.parse_args()


class Color:
    PURPLE = "\033[95m"
    CYAN = "\033[96m"
    BLUE = "\033[94m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    BOLD = "\033[1m"
    END = "\033[0m"


class Dashboard:
    """
    Dashboard for viewing progress
    """

    HEADER = """
▗▖  ▗▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖ ▗▄▄▄▖▗▄▄▄▄▖▗▄▄▄▖
▐▛▚▞▜▌▐▌   ▐▛▚▞▜▌▐▌ ▐▌  █     ▗▞▘▐▌   
▐▌  ▐▌▐▛▀▀▘▐▌  ▐▌▐▌ ▐▌  █   ▗▞▘  ▐▛▀▀▘
▐▌  ▐▌▐▙▄▄▖▐▌  ▐▌▝▚▄▞▘▗▄█▄▖▐▙▄▄▄▖▐▙▄▄▖

    """

    def __init__(self):
        self.console = Console()
        self.draw()

    def draw(self):
        self.console.clear()
        for line in self.HEADER.splitlines():
            self.console.print(f"[bold red]{line}[/bold red]")
            time.sleep(0.05)
        time.sleep(0.2)


class Question:
    """Questions csv"""

    @classmethod
    def get_solved(cls):
        payload = {
            "query": "query userProgressQuestionList($filters: UserProgressQuestionListInput) { userProgressQuestionList(filters: $filters) { totalNum questions { frontendId title  titleSlug questionStatus } } }",
            "variables": {"filters": {"skip": 0, "limit": 1000}},
        }
        response = requests.post(
            Setup.url, cookies=Setup.cookie, headers=Setup.headers, json=payload
        )
        data = response.json()
        listing = data.get("data", {}).get("userProgressQuestionList", {})
        questions = listing["questions"]
        num = listing["totalNum"]
        cls.__make_csv(num, questions)

    @staticmethod
    def __make_csv(num, question):
        file_path = Setup.create_columns()
        ids = set()
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    ids.add(row["frontendId"])

        if os.path.exists(file_path):
            with open(file_path, "a", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, Setup.columns, extrasaction="ignore")
                for record in question:
                    if (
                        record["questionStatus"] == "SOLVED"
                        and record["frontendId"] not in ids
                    ):
                        row = record.copy()
                        row["link"] = f"https://leetcode.com/{row['titleSlug']}"
                        row["priority"] = num
                        num -= 1
                        row["notes"] = ""
                        row["revised"] = False
                        writer.writerow(row)


class Reminder:
    """
    Remind each to revise for a daily question
    """

    def __init__(self):
        self.username = Setup.USERNAME


class Notes:
    """
    Adding notes to LeetCode questions
    """

    def __init__(self):
        self.id = None
        self.title = None
        self.link = None
        self.notes = None
        self.priority = None
        self.revised = None

    def add_notes_last(self):
        """
        try:
            payload = {
                "query": "query recentAcSubmissions($username: String!, $limit: Int!) { recentAcSubmissionList(username: $username, limit: $limit) {  title titleSlug timestamp } }",
                "variables": {"username": Setup.USERNAME, "limit": 1},
            }
            response = requests.post(
                Setup.url, cookies=Setup.cookie, headers=Setup.headers, json=payload
            )

            data = response.json()
            submission = data.get("data", {}).get("recentAcSubmissionList", [])
            self.title = submission[0]["title"]
            self.link = f"https://leetcode.com/{submission[0]['titleSlug']}"
            self.notes = input(
                f"{Color.BOLD}{Color.BLUE}Enter Notes for the question: {Color.END}{Color.BOLD}{Color.RED}{self.title}{Color.END}\n"
            )
            timestamp = submission[0]["timestamp"]
        except Exception as e:
            print(f"[bold red]Unexpected error occured: {e} [/bold red]")
        """
        Question().get_solved()
        notes = input(f"{Color.GREEN}Enter notes{Color.END}")
        rows = []
        fieldnames = []
        with open(Setup.csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            rows = list(reader)

        if rows:
            rows[0]["notes"] = notes
        with open(Setup.csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=Setup.columns)
            writer.writerows(rows)


class Setup:
    base_dir = os.path.dirname(os.path.abspath(__file__))
    csv_path = Path(os.path.join(base_dir, "leetnotes.csv"))
    columns = ["frontendId", "title", "link", "notes", "priority", "revised"]

    USERNAME = None
    LEETCODE_SESSION = None
    csrftoken = None
    url = None
    cookie = None
    headers = None

    def __init__(self):
        env_path = Path(__file__).resolve().parent / ".env"
        if env_path.exists():
            load_dotenv(dotenv_path=env_path)
            Setup.LEETCODE_SESSION = os.getenv("LEETCODE_SESSION")
            Setup.csrftoken = os.getenv("csrftoken")
            Setup.USERNAME = os.getenv("USERNAME")
        else:
            session = getpass.getpass(
                f"{Color.BOLD}{Color.GREEN}Enter LEETCODE_SESSION:{Color.END}\n"
            )
            token = getpass.getpass(
                f"{Color.BOLD}{Color.GREEN}Enter csrftoken:{Color.END}\n"
            )
            username = input(f"{Color.BLUE}Enter username:\n{Color.END}")
            with open(env_path, "w") as f:
                f.write(f'LEETCODE_SESSION="{session}"\n')
                f.write(f'csrftoken="{token}"\n')
                f.write(f'USERNAME="{username}"\n')
            Setup.LEETCODE_SESSION = session
            Setup.csrftoken = token
            Setup.USERNAME = username

    @classmethod
    def make_request(cls):
        cls.url = "https://leetcode.com/graphql"
        cls.cookie = {
            "LEETCODE_SESSION": Setup.LEETCODE_SESSION,
            "csrftoken": Setup.csrftoken,
        }
        cls.headers = {
            "Content-Type": "application/json",
            "Referer": "https://leetcode.com",
            "X-CSRFToken": Setup.csrftoken,
        }

    @classmethod
    def create_columns(cls):
        if not cls.csv_path.exists():
            with open(cls.csv_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(cls.columns)
        return cls.csv_path


if __name__ == "__main__":
    a = Setup()
    a.make_request()
    Notes().add_notes_last()
